# Generated by Django 4.2.23 on 2025-07-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_email',
            field=models.EmailField(max_length=254),
        ),
    ]
