# Generated by Django 4.2.23 on 2025-08-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtable',
            name='class_name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='classtable',
            name='section',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='classtable',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_class', to='main.student'),
        ),
    ]
