# Generated by Django 4.2.23 on 2025-08-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_classtable_class_name_classtable_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coures_name', models.CharField(max_length=200)),
                ('coures_price', models.CharField(max_length=200)),
                ('student', models.ManyToManyField(to='main.student')),
            ],
        ),
    ]
