# Generated by Django 4.2.23 on 2025-07-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gener',
            field=models.CharField(default='horror', max_length=200, null=True),
        ),
    ]
